### ISSUE TITLE
Google Play Store violation

### ISSUE THREAD

**Issue by neobie** [Explore-In-HMS/huawei.ads.admob_mediation#36]
Google Play store is not accepting app with this mediation.
Is there any update to fix ?

**Comment by senazincircioglu** [comment]
Hello,
We need some details to help you to solve this problem:
1. Which SDKs do you use? 
2. Did you use the latest version of ?  Huawei ads prime SDK ?
3. Please share the versions of all google-mediation-huawei dependency you use for your project.

Will be waiting for your reply.

Thank you,

Best Regards.

**Comment by deakjahn** [comment]
This is the important question before anybody invests too much work into trying it out. :-) So, instead of closing it, I would recommend to pin this issue and to keep it updated.

Google has a long history of rejecting apps with HMS code included. It isn't a question of the code being used but merely present in the executable. This is why we have to create two-flavor apps that omit HMS code when presented to the Google store and omit GMS code when presented to the Huawei store.

@neobie, do you have current epxerience whether Google still refuses apps with this package (and those it depends on) inside?
